server:
  port: 9016
spring:
  application:
    name: door-basic-parameter
#    zipkin:
#      base-url: http://localhost:9411
#    sleuth:
#        sampler:
#        #采样率值介于 0 到 1 之间，1 则表示全部采集
#        probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/metrics?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
#    sentinel:
#        transport:
#           dashboard: localhost:8998 #配置Sentinel dashboard地址
#           port: 8719
  aop:
    auto: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

